### ISSUE TITLE
Tray icon workaround for Wayland

### ISSUE THREAD

**Issue by ProjectSynchro** [lilongueti/SBZ-Linux-Applet#1]
Set `GDK_BACKEND=x11` before launching the script.

Might be worth porting this applet to something that natively supports wayland (or uses dbus for icons)

**Comment by lilongueti** [comment]
i've added the flag and now with it working under wayland i also fixed an annoying issue with gnome where it would launch a new instance instead of switching outputs,
however i placed the start logic into the new `start.py` script.
i'll look into native wayland support at some point.
Thanks

**Comment by ProjectSynchro** [comment]
Awesome!
Cheers
